### PR TITLE
gles: Fix double frees.

### PR DESCRIPTION
**Pull request by lakshmih**
Remove a few explicit frees in the redirect_buffers test which are
already handled by a wrapper.

### CODE REVIEW

**Review by bashbaug — COMMENTED** [review]
Was there truly a double free before?  Or did the `NULL` assignment prevent additional frees?

The only reason we might want to consider keeping this code as-is is because using the wrapper does change the order of the deletion slight: before this change the CL object was deleted first and the GL object was deleted second, whereas after this change the GL object is deleted first and then the CL object is deleted second.

The spec says ([link](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_Ext.html#cl_khr_gl_sharing__memobjs-lifetime-of-shared-objects)):

> If the GL object is deleted through the GL API (e.g. glDeleteBuffers, glDeleteTextures, or glDeleteRenderbuffers), subsequent use of the CL buffer or image object will result in undefined behavior, including but not limited to possible CL errors and data corruption, but may not result in program termination.

It's not entirely clear to me whether releasing the CL object would count as "use of" the CL object, but it could be considered a grey area.

**Comment by lakshmih** [comment]
There was a definite double-free - one from the explicit clReleaseMemObject and the other from assignment to NULL (which, in the wrapper calls reset and hence clReleaseMemObject once more. Almost exactly the same as other double free fixes that have been merged already, eg:
https://github.com/KhronosGroup/OpenCL-CTS/commit/4a03bb79cb8fbd6012b02783e59565cce0b1f376#diff-9453eebbcfb207de5f012c7b24338159957a13907bfc0fa1f2d779cc3cdbf7d6L351

However, the right thing in this case might be to call a reset on the wrapper object like in 
https://github.com/KhronosGroup/OpenCL-CTS/commit/12637114ac81d292861daf4bff2397a36581f712#diff-b203bd4581ecbd7f355b29ddc5c8c6d6ffc0626527d5c7dc7721a95e98d7086eL287

This would retain the relative order of release between CL/GL that you brought up.

I'll make that fix.

**Review by bashbaug — APPROVED** [review]
Thanks, latest version LGTM!

**Comment by lakshmih** [comment]
@kpet  can you review as well so we have at least two people that looked at it?

**Review by EwanC — APPROVED** [review]

**Pull request merged**
