### PR TITLE
Corrected build under msvc compiler #1833

### LINKED ISSUE #1833: isnan, isfinite, and isinf are implemented as macros for MSVC
The CTS tests currently define `isnan`, `isfinite`, and `isinf` macros for MSVC:
https://github.com/KhronosGroup/OpenCL-CTS/blob/40aaa2bcf2460a083b89427cffaacdbd5f707ffc/test_common/harness/compat.h#L141-L151

Unfortunately, this means we cannot use the functions `std::isnan`, `std::isfinite`, and `std::isinf` functions from C++11 without generating build errors on Windows only.

We should switch to the C++ versions exclusively.  Failing that, we should find another way to define these aliases that doesn't preclude using the C++ versions.  Maybe:

```c++
using isnan = std::isnan;
using isfinite = std::isfinite;
using isinf = std::isinf;
```

### PR DESCRIPTION
**Pull request by kamil-goras-mobica**
Fixes #1833 according to task description.

### CODE REVIEW

**Comment by kamil-goras-mobica** [comment]
#1833

**Comment by kamil-goras-mobica** [comment]
@bashbaug I've added correction now with using directive all calls isnan should be using std::isnan, also <cmath> is needed.

**Review by bashbaug — APPROVED** [review]
This works for me.  It's definitely a step in the right direction.

Ultimately I'd like to eliminate these "using" lines and just call the std:: versions directly, but we can do that in a follow-on PR.

**Comment by bashbaug** [comment]
Merging as discussed in the November 12th teleconference.

**Pull request merged**
