### PR TITLE
Add utility macro to skip test when an extension is not supported

### PR DESCRIPTION
**Pull request by kpet**
Use in cl_khr_external_semaphore suite as an example.

### CODE REVIEW

**Comment by kpet** [comment]
@bashbaug Here's the idea I mentioned.

**Review by bashbaug — APPROVED** [review]
Works for me!  Do you want to merge this as-is, or switch more of the tests to use the utility macro first?

Note, we may eventually want a variant that skips the test if the extension version isn't new enough, also, though we can cross that bridge when we come to it.

**Comment by kpet** [comment]
I'd suggest merging as is to make this available. It'll take a while to convert the whole code base.

> we may eventually want a variant that skips the test if the extension version isn't new enough, also, though we can cross that bridge when we come to it.

Agree x2. Almost mentioned this in the commit message. The case with a version check is a lot less common.

**Review by lakshmih — APPROVED** [review]

**Comment by bashbaug** [comment]
Merging as discussed in the December 17th teleconference.

**Pull request merged**
