### PR TITLE
Fix aliasing issue for test_half (#45)

### PR DESCRIPTION
**Pull request by julienhascoet**
OpenCL-C code must respect aliasing rules as in C99.
Therefore, accessing data from multiple pointer sizes
must all point to character type to keep strict aliasing
rules. If not, when the compiler performs optimization,
the dataflow was broken leading to failure.
We also fix the formatting and refactor few things.

### CODE REVIEW

**Comment by julienhascoet** [comment]
To help with the review due to the formatting script, here is what we actually changed to fix the aliasing violation:

```
const char *source_local2[] = {
             "__kernel void test( const __global half *p, __global float", vector_size_name_extensions[vectorSize], " *f )\n"
             "{\n"
-            "   __local ", align_types[vectorSize], " data[", local_buf_size, "/", align_divisors[vectorSize], "];\n"
+            "   __local uchar data[", local_buf_size, "/", align_divisors[vectorSize], "*sizeof(", align_types[vectorSize], ")];\n"
             "   __local half* hdata_p = (__local half*) data;\n"
             "   __global ", align_types[vectorSize], "* i_p = (__global ", align_types[vectorSize],"*)p;\n"
             "   size_t i = get_global_id(0);\n"
             "   size_t lid = get_local_id(0);\n"
             "   int k;\n"
             "   for (k=0; k<",vector_size_names[vectorSize],"/",align_divisors[vectorSize],"; k++)\n"
-            "     data[lid*",vector_size_names[vectorSize],"/",align_divisors[vectorSize],"+k] = i_p[i*",vector_size_names[vectorSize],"/",align_divisors[vectorSize],"+k];\n"
+            "     *(__local ", align_types[vectorSize], "*)&(data[(lid*",vector_size_names[vectorSize],"/",align_divisors[vectorSize],"+k)*sizeof(", align_types[vectorSize], ")]) = i_p[i*",vector_size_names[vectorSize],"/",align_divisors[vectorSize],"+k];\n"
             "   f[i] = vload", aligned ? "a" : "", "_half",vector_size_name_extensions[vectorSize],"( lid, hdata_p );\n"
             "}\n"
         };
```

**Comment by EwanC** [comment]
Would adding some intermediate variables to the kernel source to make this string literal more readable? e.g assign this to a var
```
vector_size_names[vectorSize],"/",align_divisors[vectorSize]
```

**Comment by EwanC** [comment]
https://github.com/KhronosGroup/OpenCL-CTS/issues/45 mentions using `__attribute__ ((aligned (4))) ` is that no longer needed?

**Comment by julienhascoet** [comment]
> Would adding some intermediate variables to the kernel source to make this string literal more readable? e.g assign this to a var
> 
> ```
> vector_size_names[vectorSize],"/",align_divisors[vectorSize]
> ```

Yes, I agree I'll try to propose something with defines for this.

**Comment by julienhascoet** [comment]
> #45 mentions using `__attribute__ ((aligned (4))) ` is that no longer needed?

I don't think so since local buffers are already aligned on CL_DEVICE_MIN_DATA_TYPE_ALIGN_SIZE at least.
But I may add it if you want, it shouldn't be a problem if the compiler accepts it in OpenCL-C, however, I'm not sure if existing runtime will respects it. In our implementation we align every __local buffers on the CL_DEVICE_MIN_DATA_TYPE_ALIGN_SIZE value.

**Comment by julienhascoet** [comment]
Here is the new diff to help with to review due to the format script.

```
         const char *source_local2[] = {
+           "#define VECTOR_LEN (", vector_size_names[vectorSize], "/", align_divisors[vectorSize], ")\n"
+           "#define ALIGN_TYPE ", align_types[vectorSize], "\n"
             "__kernel void test( const __global half *p, __global float", vector_size_name_extensions[vectorSize], " *f )\n"
             "{\n"
-            "   __local ", align_types[vectorSize], " data[", local_buf_size, "/", align_divisors[vectorSize], "];\n"
+            "   __local uchar data[", local_buf_size, "/", align_divisors[vectorSize], "*sizeof(ALIGN_TYPE)] __attribute__((aligned(sizeof(ALIGN_TYPE))));\n"
             "   __local half* hdata_p = (__local half*) data;\n"
-            "   __global ", align_types[vectorSize], "* i_p = (__global ", align_types[vectorSize],"*)p;\n"
+            "   __global ALIGN_TYPE* i_p = (__global ALIGN_TYPE*)p;\n"
             "   size_t i = get_global_id(0);\n"
             "   size_t lid = get_local_id(0);\n"
             "   int k;\n"
-            "   for (k=0; k<",vector_size_names[vectorSize],"/",align_divisors[vectorSize],"; k++)\n"
-            "     data[lid*",vector_size_names[vectorSize],"/",align_divisors[vectorSize],"+k] = i_p[i*",vector_size_names[vectorSize],"/",align_divisors[vectorSize],"+k];\n"
+            "   for (k=0; k<VECTOR_LEN; k++)\n"
+            "     *(__local ALIGN_TYPE*)&(data[(lid*VECTOR_LEN+k)*sizeof(ALIGN_TYPE)]) = i_p[i*VECTOR_LEN+k];\n"
             "   f[i] = vload", aligned ? "a" : "", "_half",vector_size_name_extensions[vectorSize],"( lid, hdata_p );\n"
             "}\n"
         };
```

**Review by EwanC — APPROVED** [review]
thanks for the more human readable diff of the change

**Comment by julienhascoet** [comment]
I just rebased on origin master to help with merging or cherry-pick.
I may require a new review for this. 

Thanks !

**Review by EwanC — APPROVED** [review]

**Pull request merged**
