### PR TITLE
c11_atomics - change arg type to unsigned int from signed int

### LINKED ISSUE #1030: c11_atomics - argument type do not match function returned type
See line https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/c11_atomics/common.h#L883
there is a literal `1` number give as argument so by default compiler treats this as `signed int` type. 
Reading the specification https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_C.html#atomic-functions this argument type described as M should match to C. In this case C is atomic_uint (unsigned int) because https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/c11_atomics/common.h#L718

### PR DESCRIPTION
**Pull request by gwawiork**
Fixes #1030

### CODE REVIEW

**Review by Jeremy-Kemp — APPROVED** [review]
Out of interest have you looked to see if there are any additional mismatches between `A` and `M`?

**Comment by gwawiork** [comment]
> Out of interest have you looked to see if there are any additional mismatches between `A` and `M`?

Hi Jeremy, sorry I do not understand your question.

**Comment by Jeremy-Kemp** [comment]
Sorry it was badly written!

I was checking that there were no more signed/unsigned mismatches but I've had a look and can't see any.

**Comment by gwawiork** [comment]
Ok I have not noticed any more issues.

**Pull request merged**
