### PR TITLE
Restored the embedded reduction factor to bruteforce.

### LINKED ISSUE #1045: Bruteforce is missing the embedded reduction factor
During the consolidation of CTS from GitLab, it seems that the embedded reduction factor that was present in the bruteforce test has been lost.

Other tests (such as conversions) retained the reduction factor.

This issue tracks re-adding the reduction factor into bruteforce.

### PR DESCRIPTION
**Pull request by Jeremy-Kemp**
This change was present on the GitLab branch but missed out during the transition to GitHub.

This change is intentionally as close as possible to the patch on GitLab.

Fixes #1045

### CODE REVIEW

**Comment by EwanC** [comment]
Trying to find `EMBEDDED_REDUCTION_FACTOR ` in [gitlab](https://gitlab.khronos.org/opencl/conformance-tests/-/tree/master) to compare. Was it on a particular branch? Only seeing search hits in the conversions tests

**Review by EwanC — DISMISSED** [review]

**Review by kpet — COMMENTED** [review]
Could the scaling logic be extracted out as a (small) number of utility functions? It seems 2 different blocks of code are repeated over and over.

**Comment by Jeremy-Kemp** [comment]
@kpet I've created the helper functions and used them in locations that this change requires.

**Review by kpet — DISMISSED** [review]
Thanks, this will make maintenance easier.

I find the `set*` name a bit confusing as the functions don't mutate any state. `get*` or `calc*` or something would have been clearer IMHO.

**Review by EwanC — DISMISSED** [review]
> I find the set* name a bit confusing as the functions don't mutate any state. get* or calc* or something would have been clearer IMHO.

Would also have a preference for `get*` etc, but LGTM otherwise

**Comment by Jeremy-Kemp** [comment]
I've pushed a change that simply renames the `get*` functions to `set*` instead.

**Review by EwanC — APPROVED** [review]

**Review by kpet — APPROVED** [review]

**Pull request merged**
