### PR TITLE
Fix return-type warnings with harness library and basic test

### PR DESCRIPTION
**Pull request by layog**
Reproduction steps - Compile with flags `-Werror -Wreturn-type`

### CODE REVIEW

**Comment by layog** [comment]
@kpet Agreed. I wanted to do that but since it's my first commit to this repo, I kept it small.

There are no C dependencies in the code. I'll confirm that and will push upstream.

**Comment by kpet** [comment]
@layog Makes sense, thanks!

**Comment by keryell** [comment]
Just curious: why is there C++ code at the first place in a CTS checking for a C API?

**Comment by layog** [comment]
@keryell I am not sure whether this question is related to this PR.
In general, OpenCL's C-style API is fully accessible through C++ and there is C++ style API as well.

**Comment by keryell** [comment]
I found just curious to have C++ code in the CTS for a C API. How a host without a C++ compiler can pass the CTS? It is just a question out of the blue...

**Comment by jrprice** [comment]
> How a host without a C++ compiler can pass the CTS?

Cross-compile static binaries from a system that does have a C++ compiler?

**Comment by keryell** [comment]
It does not really change the problem: you need a a C++ cross-compiler at the first place. Then you hope the target has enough memory to fit the C++ runtime...

**Pull request merged**
