### PR TITLE
gles: Fix compile errors.

### PR DESCRIPTION
**Pull request by lakshmih**
For 32 and 64-bit Visual Studio and the Android Q NDK.

### CODE REVIEW

**Comment by gwawiork** [comment]
I am trying to compile this on Windows using MSVC but it fails with error:
`cannot open source files: EGL/egl.h`
Where to get these headers and where they should be placed ?
Any additional pre-setup need to be done ?

**Comment by gwawiork** [comment]
> > I am trying to compile this on Windows using MSVC but it fails with error:
> > `cannot open source files: EGL/egl.h`
> > Where to get these headers and where they should be placed ?
> > Any additional pre-setup need to be done ?
> 
> "EGL/egl.h" and the libraries EGL and GLESv2 (with OS specific prefixes/suffixs in the file names) need to be provided by the vendor doing the testing in the same way that the CL equivalents need to be provided. This can be done by putting the EGL headers and libraries alongside the CL variants referred to by CL_INCLUDE_DIR and CL_LIB_DIR CMake variables.

ok Thanks. I could not find any lib for Windows so I suppose this test suite is not supported on Windows. On Linux I got errors which showed me that the PR #949 have to be merged first.

**Review by Jeremy-Kemp — COMMENTED** [review]
I've tested this out on an implementation that doesn't support gles and it does not cause any issues.

**Review by gwawiork — DISMISSED** [review]
LGTM

**Review by kpet — APPROVED** [review]

**Comment by kpet** [comment]
@lakshmih Could you rebase this so it gets tested by the now-fixed CI please?

**Review by kpet — APPROVED** [review]

**Comment by kpet** [comment]
Merging since this was reviewed several times already.

**Pull request merged**
