### PR TITLE
Replace Travis CI with Github Actions

### PR DESCRIPTION
**Pull request by kpet**
Signed-off-by: Kevin Petit <kevin.petit@arm.com>

### CODE REVIEW

**Comment by gwawiork** [comment]
Should we change this variable as well? 
https://github.com/kpet/OpenCL-CTS/blob/actions/presubmit.sh#L44 
`${TRAVIS_OS_NAME} == "linux"`

**Comment by kpet** [comment]
Good catch, will try to fix as part of this PR.

**Comment by kpet** [comment]
@gwawiork Now fixed. PTAL.

**Review by gwawiork — APPROVED** [review]
LGTM

**Comment by kpet** [comment]
Merging this despite the single review to get the CI going again ASAP.

**Pull request merged**
