### PR TITLE
Deduplicate test_basic int2float/float2int

### PR DESCRIPTION
**Pull request by JohnKesapidesARM**
Merge int2float,float2int.

Signed-off-by: John Kesapides <john.kesapides@arm.com>

### CODE REVIEW

**Review by EwanC — DISMISSED** [review]
LGTM

**Comment by lakshmih** [comment]
Reviewing

**Comment by lakshmih** [comment]
Reviewing

**Comment by bashbaug** [comment]
Needs one more week for review.  Also needs the merge conflict fixed.

**Review by lakshmih — APPROVED** [review]
Looks good.

**Comment by JohnKesapidesARM** [comment]
Rebased

**Review by EwanC — APPROVED** [review]

**Comment by alan-baker** [comment]
Was there a reason test_float2int.cpp was not deleted?

**Pull request merged**
