### PR TITLE
test allocations: restore small number of work items in case of reduction 

### PR DESCRIPTION
**Pull request by gwawiork**

### CODE REVIEW

**Comment by gwawiork** [comment]
@kpet This is related to https://github.com/KhronosGroup/OpenCL-CTS/pull/1852
We use reduction argument on simulation then too high number of work items makes test very long and we see timeouts. Would be nice have previous value set. I agree there is a need to implement function which will calculate this number accordingly

**Comment by kpet** [comment]
Merging this PR would result in failures for the implementations listed in #1852. Is the issue you're seeing on a final device or development environment? If the latter, maybe we could introduce command line options to help.

**Comment by gwawiork** [comment]
> Merging this PR would result in failures for the implementations listed in #1852. Is the issue you're seeing on a final device or development environment? If the latter, maybe we could introduce command line options to help.

By default value is set as in #1852  Only when someone use reduction factor (percentage in command line) Do you use it ?
`if (g_reduction_percentage != 100)`

**Review by kpet — APPROVED** [review]

**Comment by kpet** [comment]
@gwawiork Apologies I'd missed that when quickly skimming through it. I've now approved the PR. Should be fine.

**Comment by bashbaug** [comment]
Discussed in the April 16th teleconference.  We'll give this one more week for review, but are hoping to merge shortly.

**Review by lakshmih — APPROVED** [review]

**Comment by bashbaug** [comment]
Merging as discussed in the May 21st teleconference.

**Pull request merged**
