### PR TITLE
Deduplicate test_basic image_array_copy

### PR DESCRIPTION
**Pull request by JohnKesapidesARM**
Merge image_array_copy, image_array_copy3d
as they share a lot of common code.

Signed-off-by: John Kesapides <john.kesapides@arm.com>

### CODE REVIEW

**Review by EwanC — APPROVED** [review]

**Comment by kpet** [comment]
2024/07/02 teleconference: @JohnKesapidesARM This needs rebasing.

**Comment by ahesham-arm** [comment]
> 2024/07/02 teleconference: @JohnKesapidesARM This needs rebasing.

@kpet Rebased and all CI checks passing.

**Review by EwanC — APPROVED** [review]
LGTM - Trusting the 2022 review I did here and looking at the `test_imagearraycopy.cpp` diff from the rebase (which is small)

**Comment by bashbaug** [comment]
Merging as discussed in the July 9th teleconference.

**Pull request merged**
