### PR TITLE
 Fix enqueue_flags test to use correct barrier type. 

### PR DESCRIPTION
**Pull request by nikhiljnv**
Fix enqueue_flags test to use correct barrier type.

Currently, enqueue_flags test uses CLK_LOCAL_MEM_FENCE.
Use CLK_GLOBAL_MEM_FENCE instead as all threads across work-groups
need to wait here.

### CODE REVIEW

**Comment by alycm** [comment]
Hi Nikhil, although your immediate commit (https://github.com/KhronosGroup/OpenCL-CTS/commit/62232ae47b81c2a2a45e4818f7f22314b6f5e6d4) matched the PR description, you then force pushed a change that overrode that.

**Comment by nikhiljnv** [comment]
> 
> 
> Hi Nikhil, although your immediate commit ([62232ae](https://github.com/KhronosGroup/OpenCL-CTS/commit/62232ae47b81c2a2a45e4818f7f22314b6f5e6d4)) matched the PR description, you then force pushed a change that overrode that.

Fixed the message to reflect forced update.
Will create separate pull request for the original change.

**Comment by kpet** [comment]
@nikhiljnv Ping :). Could you open PRs against cl20_trunk and cl21_trunk as well please?

**Comment by nikhiljnv** [comment]
Created https://github.com/KhronosGroup/OpenCL-CTS/pull/348 and https://github.com/KhronosGroup/OpenCL-CTS/pull/349 for cl20_trunk and cl21_trunk.

**Pull request merged**
