### PR TITLE
Fix build breakage introduced by #1911

### PR DESCRIPTION
**Pull request by lakshmih**

### CODE REVIEW

**Comment by lakshmih** [comment]
1911 is breaking the Android build for us, so would appreciate if this fix or an equivalent one could be reviewed and merged.

**Comment by svenvh** [comment]
@okias since you authored #1911: does this proposed fix still work with your use case?

**Comment by okias** [comment]
@svenvh still working properly for musl-libc, thanks for the ping!

**Review by svenvh — APPROVED** [review]

**Comment by bashbaug** [comment]
Merging as discussed in the May 7th teleconference.

Two areas for follow-up:
* Can we do this check in CMake, to choose the right version of `strerror_r`?
* Why wasn't this break found in CI?

**Pull request merged**
