### PR TITLE
Fix local memory out of bounds issue in `atomic_fence`

### PR DESCRIPTION
**Pull request by Jeremy-Kemp**
In the error condition, the atomic_fence kernel can illegally access local memory addresses.

In this snippet, `localValues` is in the local address space and provided as a kernel argument. Its size is effectively `get_local_size(0) * sizeof(int)`. The stores to `localValues` lead to OoB accesses.

```C
  size_t myId = get_local_id(0);

  ...

  if(hisAtomicValue != hisValue)
  { // fail
    atomic_store(&destMemory[myId], myValue-1);
    hisId = (hisId+get_local_size(0)-1)%get_local_size(0);
    if(myValue+1 < 1)
      localValues[myId*1+myValue+1] = hisId;
    if(myValue+2 < 1)
      localValues[myId*1+myValue+2] = hisAtomicValue;
    if(myValue+3 < 1)
      localValues[myId*1+myValue+3] = hisValue;
  }
```

### CODE REVIEW

**Review by gwawiork — APPROVED** [review]
LGTM

**Review by lakshmih — COMMENTED** [review]
[Qualcomm] This change looks okay to us.

**Comment by bashbaug** [comment]
Merging as agreed on the May 31 teleconference once the merge conflict is resolved.

**Comment by bashbaug** [comment]
The merge conflict still exists - @paulfradgley  is this something you can help with?  I think the merge conflicts are clang-format-related, so reformmating this file and rebasing may be all that is required.

**Comment by paulfradgley** [comment]
I had trouble updating this PR, so I made a new one from my own branch #1437

**Comment by bashbaug** [comment]
Closing - replaced by https://github.com/KhronosGroup/OpenCL-CTS/pull/1437

**Pull request closed without merging**
