### PR TITLE
Reformat test harness code

### PR DESCRIPTION
**Pull request by StuartDBrady**
This goes part of the way to fixing issue #625.

Signed-off-by: Stuart Brady <stuart.brady@arm.com>

### CODE REVIEW

**Comment by bashbaug** [comment]
This change needs a rebase now.

Is this purely a formatting change, with no functional changes?  If so, let's try to get this merged ASAP after rebasing.  It'll make future code reviews much easier since diffs should be smaller.

**Comment by alycm** [comment]
I haven't actually reviewed this, but if it is a 100% automatic formatting I agree with this principle and don't need to read the code changes.  And yes, lets just merge quickly on a rebase rather hit conflicts again.

**Comment by Jeremy-Kemp** [comment]
Agree, lets get this in quickly once its been rebased.

This poses the question, if we're going to start applying the format to entire files, should we just do the entire tree in one go to get it over and done with?

**Comment by kpet** [comment]
We still have some fairly large downstream patches in the image tests that we'd want to unpick/upstream before the entire tree is formatted.

**Comment by StuartDBrady** [comment]
Okay, will rebase this.

**Review by kpet — APPROVED** [review]
Automatic formatting changes only. Merging now so it doesn't go stale again.

**Pull request merged**
