### PR TITLE
Added new tests to verify negative results of clEnqueueSignalSemaphoresKHR

### PR DESCRIPTION
**Pull request by shajder**
According to work plan from issue https://github.com/KhronosGroup/OpenCL-CTS/issues/1691

### CODE REVIEW

**Comment by nikhiljnv** [comment]
@shajder Can you fix conflicts on TOT?

**Comment by shajder** [comment]
@nikhiljnv that might be a bit difficult, I am on my vacation without mobica workstation... but I can make you a collaborator of my fork if you have time to solve those conflicts, otherwise I can do that right after I get back to work.

**Comment by shajder** [comment]
> @shajder Can you fix conflicts on TOT?

@nikhiljnv conflicts solved.

**Comment by joshqti** [comment]
Qualcomm is OK with this change

**Comment by shajder** [comment]
close/open to retrigger CI

**Review by nikhiljnv — APPROVED** [review]

**Review by lakshmih — APPROVED** [review]

**Pull request merged**
