### PR TITLE
Remove unused code in clCopyImage

### PR DESCRIPTION
**Pull request by radszy**
Some of the declarations that are still used now moved to testBase.h
as these are reused throughout the image tests.

Signed-off-by: Radek Szymanski <radek.szymanski@arm.com>

### CODE REVIEW

**Review by kpet — DISMISSED** [review]
LGTM, thanks!

**Comment by jlewis-austin** [comment]
Anybody know why the gUseRamp feature went away? I occasionally find it useful and was debating whether to try reimplementing it or not.

**Comment by gwawiork** [comment]
what about removing unused sections from test_copy_2D_2D_array.cpp like from other files

**Comment by kpet** [comment]
@jlewis-austin No idea when/how it disappeared. I suggest you create a separate issue to discuss this.

**Comment by radszy** [comment]
@gwawiork Thanks for catching that, not sure how this happened.

**Review by kpet — APPROVED** [review]

**Review by gwawiork — APPROVED** [review]
LGTM

**Pull request merged**
