### PR TITLE
A first set of updates to the submission template

### PR DESCRIPTION
**Pull request by kpet**
Signed-off-by: Kevin Petit <kevin.petit@arm.com>

### CODE REVIEW

**Review by bashbaug — APPROVED** [review]
This generally looks good to me.

Regarding removal of `CL_DEVICE_MAX_CLOCK_FREQUENCY`, I think this is fine, but I'd consider removing many (most? all?) of the other device queries also.  The current list of device queries seems fairly arbitrary, and the comprehensive list of device queries can be found in the `test_computeinfo` output if needed.

**Comment by kpet** [comment]
Yes, as discussed in the 2020/09/23 teleconference, removing only this one was arbitrary and I used it as a discussion starter since it seemed the most out of place. Still as discussed in the teleconference, I want us to remove all of these as the conformance process means that the value will be captured in the test logs anyway.

**Review by Jeremy-Kemp — APPROVED** [review]
Echo what @bashbaug said.

I don't think it should block this PR though.

**Comment by kpet** [comment]
Two approvals from two implementers. Merging to allow further changes on top.

**Pull request merged**
