### PR TITLE
Turn on building test_gl in travis

### PR DESCRIPTION
**Pull request by gwawiork**
Add building test_gl binaries on Ubuntu - reopen #803

### CODE REVIEW

**Comment by gwawiork** [comment]
Could somebody help? :
- build job 1 (Ubuntu) it will work (fix in PR #802 )
- build job 2 (OSx).  Does somebody know how to add GL headers on OSx ?
- build job 4 and build job 5 (Ubuntu) - at first look I do not see reason why this do not work as for job 1. What are the differences in system configuration between them ?

**Comment by kpet** [comment]
The Arm and AArch64 jobs are using cross-compilation so the native GL libs won't help. Either we need Arm or AArch64 GL libs or maybe we can disable GL for these jobs.

For Mac, I don't really know. @jrprice Any insights?

**Comment by jrprice** [comment]
> For Mac, I don't really know. @jrprice Any insights?

OpenGL is deprecated on Apple, so I'm not sure it's useful to test this. You can add `-DGL_SILENCE_DEPRECATION` to the compiler options, but I get various other errors when I do this on my machine.

**Comment by kpet** [comment]
Right, we should probably only enable GL in native Linux builds then. Some coverage is still infinitely better than none.

**Comment by gwawiork** [comment]
Thank you for your suggestions. I've turned on GL only on native linux builds. Having merged #803 this build should pass

**Comment by kpet** [comment]
@gwawiork The CI changes look good and the Linux job now fails as expected. Could you fold https://github.com/KhronosGroup/OpenCL-CTS/pull/802 into this PR so we can see that it fixes the issues?

**Comment by gwawiork** [comment]
Added commits from #802

**Comment by kpet** [comment]
@gwawiork Looks like it isn't building: https://travis-ci.org/github/KhronosGroup/OpenCL-CTS/builds/699338622

**Pull request merged**
