### PR TITLE
Deduplicate write_image

### PR DESCRIPTION
**Pull request by JohnKesapidesARM**
Merge writeimage,writeimage_int16,writeimage_fp32
as they share a lot of common code.

Signed-off-by: John Kesapides <john.kesapides@arm.com>

### CODE REVIEW

**Comment by lakshmih** [comment]
Qualcomm is okay with this change

Sreelakshmi Haridas Maruthur
Qualcomm

**Review by lakshmih — DISMISSED** [review]

**Comment by bashbaug** [comment]
This has a merge conflict now but is otherwise ready to be merged.

**Comment by JohnKesapidesARM** [comment]
> This has a merge conflict now but is otherwise ready to be merged.

Merge conflict should be resolved now :)

**Review by bashbaug — COMMENTED** [review]
This may not be a concern, but just to double-check:

I did a spot-check which kernels were executed before and after this change and we executed each kernel 2x before this change vs. 1x after this change.

Here are the list of kernels executed on our GPU before the change:

```
test_bgra8888_write SIMD32 GWS[ 512 x 512 ] LWS[ NULL ],      2,        505916,    4.47%,        252958,        169666,        336250
  test_rgba16_write SIMD32 GWS[ 512 x 512 ] LWS[ NULL ],      2,       1028916,    9.10%,        514458,        507000,        521916
test_rgba8888_write SIMD32 GWS[ 512 x 512 ] LWS[ NULL ],      2,        327749,    2.90%,        163874,        154416,        173333
test_rgbaFFFF_write SIMD32 GWS[ 512 x 512 ] LWS[ NULL ],      2,       2013666,   17.81%,       1006833,        994666,       1019000
```

Here are the kernels executed after this change:

```
 test_CL_BGRACL_UNORM_INT8 SIMD32 GWS[ 512 x 512 ] LWS[ NULL ],      1,        295833,    4.11%,        295833,        295833,        295833
      test_CL_RGBACL_FLOAT SIMD32 GWS[ 512 x 512 ] LWS[ NULL ],      1,       1047249,   14.56%,       1047249,       1047249,       1047249
test_CL_RGBACL_UNORM_INT16 SIMD32 GWS[ 512 x 512 ] LWS[ NULL ],      1,        525416,    7.30%,        525416,        525416,        525416
 test_CL_RGBACL_UNORM_INT8 SIMD32 GWS[ 512 x 512 ] LWS[ NULL ],      1,        331666,    4.61%,        331666,        331666,        331666
```

It seems like the kernels were executed twice to check behavior when the image being written was created with `CL_MEM_READ_WRITE` and `CL_MEM_WRITE_ONLY`.  After this change, we are only checking for the case with `CL_MEM_WRITE_ONLY`.  Are we OK with this change (maybe we have coverage elsewhere)?  Or should we add back checking for `CL_MEM_READ_WRITE` in addition to `CL_MEM_WRITE_ONLY`?

**Comment by JohnKesapidesARM** [comment]
> This may not be a concern, but just to double-check:
> 
> I did a spot-check which kernels were executed before and after this change and we executed each kernel 2x before this change vs. 1x after this change.
> 
> Here are the list of kernels executed on our GPU before the change:
> 
> ```
> test_bgra8888_write SIMD32 GWS[ 512 x 512 ] LWS[ NULL ],      2,        505916,    4.47%,        252958,        169666,        336250
>   test_rgba16_write SIMD32 GWS[ 512 x 512 ] LWS[ NULL ],      2,       1028916,    9.10%,        514458,        507000,        521916
> test_rgba8888_write SIMD32 GWS[ 512 x 512 ] LWS[ NULL ],      2,        327749,    2.90%,        163874,        154416,        173333
> test_rgbaFFFF_write SIMD32 GWS[ 512 x 512 ] LWS[ NULL ],      2,       2013666,   17.81%,       1006833,        994666,       1019000
> ```
> 
> Here are the kernels executed after this change:
> 
> ```
>  test_CL_BGRACL_UNORM_INT8 SIMD32 GWS[ 512 x 512 ] LWS[ NULL ],      1,        295833,    4.11%,        295833,        295833,        295833
>       test_CL_RGBACL_FLOAT SIMD32 GWS[ 512 x 512 ] LWS[ NULL ],      1,       1047249,   14.56%,       1047249,       1047249,       1047249
> test_CL_RGBACL_UNORM_INT16 SIMD32 GWS[ 512 x 512 ] LWS[ NULL ],      1,        525416,    7.30%,        525416,        525416,        525416
>  test_CL_RGBACL_UNORM_INT8 SIMD32 GWS[ 512 x 512 ] LWS[ NULL ],      1,        331666,    4.61%,        331666,        331666,        331666
> ```
> 
> It seems like the kernels were executed twice to check behavior when the image being written was created with `CL_MEM_READ_WRITE` and `CL_MEM_WRITE_ONLY`. After this change, we are only checking for the case with `CL_MEM_WRITE_ONLY`. Are we OK with this change (maybe we have coverage elsewhere)? Or should we add back checking for `CL_MEM_READ_WRITE` in addition to `CL_MEM_WRITE_ONLY`?

@bashbaug  Thanks for spotting this. These changes shouldn't reduce coverage. I'll rework it a bit, to test for CL_MEM_READ_WRITE as well

**Review by bashbaug — APPROVED** [review]
Thanks, latest version has the same number of kernels now :thumbsup:.

```
       test_CL_BGRACL_UNORM_INT8,      2,        396166,    3.55%,        198083,        196583,        199583
            test_CL_RGBACL_FLOAT,      2,       2100833,   18.81%,       1050416,       1048750,       1052083
      test_CL_RGBACL_UNORM_INT16,      2,        991916,    8.88%,        495958,        494583,        497333
       test_CL_RGBACL_UNORM_INT8,      2,        576082,    5.16%,        288041,        227666,        348416
```

**Pull request merged**
