### PR TITLE
[api][test_zero_sized_enqueue] Add CL_SUBMITTED check for waiting status

### PR DESCRIPTION
**Pull request by Nuullll**
This addresses #1011

### CODE REVIEW

**Review by gwawiork — APPROVED** [review]
LGTM

**Review by EwanC — APPROVED** [review]

**Comment by kpet** [comment]
Not sure this is correct. For the event to have a CL_SUBMITTED status, the command must have been flushed.

> Submitted [...] The transition into this state occurs when the command is flushed from the command-queue

The specification defines a number of points at which ways a command can be flushed but it says nothing about implementations flushing commands

A command may reside in the queue until it is flushed either explicitly (a call to clFlush) or implicitly by some other command.

Because commands in a command-queue are not required to begin execution until the command-queue is flushed,

**Comment by EwanC** [comment]
> A command may reside in the queue until it is flushed either explicitly (a call to clFlush) or implicitly by some other command.
> 
> Because commands in a command-queue are not required to begin execution until the command-queue is flushed,

If I'm following right, would it be valid implementation behavior for the `clEnqueueNDRangeKernel` command [here](https://github.com/KhronosGroup/OpenCL-CTS/pull/1012/files#diff-d20cbf2cacd34ebd1ab5bb997c7e1206e482f8ad208db6da44c63d1876e32993R140)
to implicitly flush? Therefore setting the event status to `CL_SUBMITTED`

**Comment by kpet** [comment]
That's what is unclear to me. The spec provides a detailed list of commands that MUST "perform an implicit" flush but it doesn't clearly state whether doing so from another API call or even independently of any API call is allowed or forbidden.

**Comment by Nuullll** [comment]
> That's what is unclear to me. The spec provides a detailed list of commands that MUST "perform an implicit" flush but it doesn't clearly state whether doing so from another API call or even independently of any API call is allowed or forbidden.

Thanks, I agree that the spec is unclear about this part.

I guess a conformance test should only valid the behaviors explicitly stated in the spec. In such a case, I think it's possibly an implementation-defined behavior that doesn't violate the current spec.
Or should we require an update in spec to clarify this issue? I'm not familiar with the OpenCL spec drafting process :P

**Comment by kpet** [comment]
As documented on https://github.com/KhronosGroup/OpenCL-Docs/issues/479, the WG agrees that flushing should be permitted at any time. Merging this change.

**Pull request merged**
