### PR TITLE
Fix literal integer types for atomics tests

### PR DESCRIPTION
**Pull request by zsrkmyn**

### CODE REVIEW

**Comment by zsrkmyn** [comment]
I have no idea why the format check failed. Should I change the format accordingly?

**Comment by EwanC** [comment]
> 
> 
> I have no idea why the format check failed. Should I change the format accordingly?

Yeah, run `clang-format-9` through `git-clang-format` as per https://github.com/KhronosGroup/OpenCL-CTS/blob/master/check-format.sh

**Comment by zsrkmyn** [comment]
Done. Thanks.

**Comment by zsrkmyn** [comment]
A soft ping.

**Review by gwawiork — APPROVED** [review]
LGTM

**Review by nikhiljnv — APPROVED** [review]
LGTM. Approved.

**Comment by zsrkmyn** [comment]
Hi @nikhiljnv, as I don't have the write access, could you help merge it? Many thanks! :-)

**Pull request merged**
