### PR TITLE
Accept OpenCL 3.0 in version parsing code and use where appropriate

### LINKED ISSUE #751: Add support for parsing OpenCL 3.0 to Version and replace uses of 2.2 experimental with 3.0
There are a number of conditions comparing the reported version to 2.2 instead of 3.0.

### PR DESCRIPTION
**Pull request by kpet**
There were a number of tests against 2.2 that are clearer against 3.0.

Fixes #751

Signed-off-by: Kévin Petit <kpet@free.fr>

### CODE REVIEW

**Comment by gwawiork** [comment]
LGTM, only format error need to be fix.
I think we should run format conversion for all files to avoid such errors

**Comment by jrprice** [comment]
Now that the headers have been updated to move the 3.0 symbols from `CL_EXPERIMENTAL` to `CL_VERSION_3_0`, the code guarded by these dynamic checks won't compile under Travis CI (hence why other PRs are failing CI). We'd either need to change the `#ifdef CL_EXPERIMENTAL` guards to `#ifdef CL_VERSION_3_0`, or just make 3.0 the default and remove the `#ifdef CL_EXPERIMENTAL` guards altogether.

**Comment by kpet** [comment]
I think my vote goes to removing the guards. Should I do that under this PR and widen the scope to "basic changes to support CL3"?

**Comment by jrprice** [comment]
> I think my vote goes to removing the guards. Should I do that under this PR and widen the scope to "basic changes to support CL3"?

Yes, sounds good to me, thanks!

**Comment by jrprice** [comment]
The `CMakeLists.txt` file will also need to be updated to enable 3.0 in the headers.

**Comment by kpet** [comment]
Yup just spotted that I forgot to commit this.

**Comment by kpet** [comment]
Merging this to fix CI.

**Pull request merged**
