### PR TITLE
fix indentation of test_waitlists.cpp

### PR DESCRIPTION
**Pull request by matthiasdiener**
Followup of #1458

### CODE REVIEW

**Comment by matthiasdiener** [comment]
This is ready for review. Currently, compilation of this test fails due to `-Wmisleading-indentation`.

**Review by StuartDBrady — APPROVED** [review]
LGTM.

**Comment by StuartDBrady** [comment]
@matthiasdiener, am wondering why this wasn't caught by the build checks (GitHub Actions)—do you have any suggestions?

(My best guess right now is that this is caused by differences in what is flagged as misleading indentation by different compilers—the version of GCC that I'm using did not catch this, nor did that used for our automated builds, but other GCC versions may do, as may Clang—so presumably that is what happened here.)

**Comment by matthiasdiener** [comment]
> @matthiasdiener, am wondering why this wasn't caught by the build checks (GitHub Actions)—do you have any suggestions?
> 
> (My best guess right now is that this is caused by differences in what is flagged as misleading indentation by different compilers—the version of GCC that I'm using did not catch this, nor did that used for our automated builds, but other GCC versions may do, as may Clang—so presumably that is what happened here.)

This seems like the most likely explanation - I saw this warning with gcc 11.3.0-5 from Debian testing.

**Pull request merged**
