### PR TITLE
specialization constant test fixes

### LINKED ISSUE #911: Address remaining minor comments in #719
https://github.com/KhronosGroup/OpenCL-CTS/pull/719

### PR DESCRIPTION
**Pull request by bashbaug**
This fixes the few minor issues remaining from #719.  Specifically:

* Removes use of the `SPV_KHR_no_integer_wrap_decoration` extension since it is not needed for these tests.
* Removes the unused `notEqual` function argument.
* Removes an unnecessary `clFinish`.

Fixes #911.

### CODE REVIEW

**Comment by gwawiork** [comment]
What about adding script assemble_spirv.py ? it is already in another PR which is not merged yet https://github.com/KhronosGroup/OpenCL-CTS/pull/902

**Comment by bashbaug** [comment]
> What about adding script assemble_spirv.py ? it is already in another PR which is not merged yet #902

Ah, I was surprised not to see an existing script that does this, and #902 slipped below my radar since it's not on the OpenCL 3.0 board.  The script in #902 looks better than this one.  I'll remove this script (for now).  Let's get #902 merged soon though!

**Review by kpet — APPROVED** [review]
LGTM!

**Review by gwawiork — APPROVED** [review]
LGTM

**Pull request merged**
