### PR TITLE
Enable test_vulkan by default in presubmit

### PR DESCRIPTION
**Pull request by nikhiljnv**
Enable test_vulkan by default in presubmit

test_vulkan is disabled by default as part of
PR #1530.
Given the ongoing development to test_vulkan,
it is important to have this enabled in CI builds
to avoid breaking test builds.
Enable the test build as part of presubmit script.

### CODE REVIEW

**Comment by svenvh** [comment]
> [nikhiljnv](https://github.com/nikhiljnv) wants to merge 77 commits into [KhronosGroup:main](https://github.com/KhronosGroup/OpenCL-CTS)

I'd suggest to tidy up this PR by rebasing the actual commit you'd like to merge against the latest `main` branch.

**Comment by nikhiljnv** [comment]
> > [nikhiljnv](https://github.com/nikhiljnv) wants to merge 77 commits into [KhronosGroup:main](https://github.com/KhronosGroup/OpenCL-CTS)
> 
> I'd suggest to tidy up this PR by rebasing the actual commit you'd like to merge against the latest `main` branch.

It's the commit history that is bit strange, but the change itself is clean and can be merged to main with commit history squeezed. 
I will take a look at cleaning up commit history.

**Comment by nikhiljnv** [comment]
Created https://github.com/KhronosGroup/OpenCL-CTS/pull/1655 with cleaner commit history.

**Comment by svenvh** [comment]
Thanks, closing this in favor of #1655.

**Pull request closed without merging**
