### PR TITLE
Partial clean up of test_compiler_defines_for_extensions

### PR DESCRIPTION
**Pull request by StuartDBrady**
Replace repetitions of extensions_supported[num_of_supported_extensions] with a single pointer variable.

Replace character-by-character comparisons with a new string_has_prefix function.

Signed-off-by: Stuart Brady <stuart.brady@arm.com>

### CODE REVIEW

**Comment by StuartDBrady** [comment]
I am of the opinion that this should code should be converted over to use C++ strings, vectors, etc. in due course, and that the log messages could be improved, but I have decided to limit this change to making better use of C strings for now, so that it is easier to review.

**Comment by StuartDBrady** [comment]
Note that the strictly speaking, the comparison `memcmp(extensions_supported[num_of_supported_extensions], "cles_khr_", 9)` could go out of bounds, if the extension name is allocated towards the the end of a page and is shorter than "cles_khr_" – this is _very_ unlikely, to the point of being mostly theoretical, so I have chosen not to mention this in the commit message.

**Review by EwanC — APPROVED** [review]

**Comment by bcalidas** [comment]
Qualcomm would like some more time to review this change.

**Comment by bashbaug** [comment]
Merging as discussed in the December 13th teleconference.

**Pull request merged**
