### PR TITLE
Fix inconsistent dll linking warnings for VS 2015/17 (#466)

### LINKED ISSUE #466: Fix windows "inconsistent dll linkage" build warnings
With VS2015 and above, building the CTS produces several MB worth of warnings pertaining to duplicate definitions, e.g.
`7>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\corecrt_math.h(576): note: see previous definition of 'rintf'
7>C:\wsl\ocl_cts\OpenCL-CTS\test_common\harness/compat.h(158): warning C4273: 'rintl': inconsistent dll linkage`

Affected functions should be removed from compat.h and msvc9.c for newer MSVC versions.

### PR DESCRIPTION
**Pull request by jlewis-austin**
-- #ifdef out duplicate definitions
-- remove make_nan() dead code

Fixes #466

### CODE REVIEW

**Comment by jlewis-austin** [comment]
BTW, I noticed that test_conversions and test_geometrics still compile with debug flags. Some of the implementations removed here (e.g. rintf) use algorithms that look like they could be brittle to optimizations. I'm wondering if those flags can be removed for the newer compilers at least (or better yet fix the affected algorithms)? I don't know how to verify that on all possible compilers though...

**Comment by gwawiork** [comment]
Could you give me one day more for deep verification please :) ? In general looks ok

**Comment by kpet** [comment]
@gwawiork Thanks!

@jlewis-austin I'm tempted to suggest we remove the debug flags and start from there. They shouldn't be hardcoded, especially if we can't tie their presence to a specific compiler/issue.

**Comment by jlewis-austin** [comment]
> I'm tempted to suggest we remove the debug flags and start from there. They shouldn't be hardcoded, especially if we can't tie their presence to a specific compiler/issue.

@kpet I agree; will open a new issue for that.

**Comment by gwawiork** [comment]
verification passed. can be merged

**Comment by kpet** [comment]
@jlewis-austin @gwawiork  Thanks! Merging.

**Pull request merged**
