### PR TITLE
Removed usage of half types in CTS test

### PR DESCRIPTION
**Pull request by kamil-goras-mobica**
#1982

### CODE REVIEW

**Review by bashbaug — CHANGES_REQUESTED** [review]
This isn't the correct fix - sorry for poorly explaining what needs to be done!

We want to keep the testing for `CL_HALF_FLOAT`.  In other words, we shouldn't lose any test covereage after making these changes.

We want to remove the dependency on `cl_khr_fp16` for these tests though, so the tests that currently require `cl_khr_fp16` (which are used to test `CL_HALF_FLOAT`) need to be modified.

See the discussion here: https://github.com/KhronosGroup/OpenCL-CTS/pull/1974

One possible solution would be to eliminate all usage pointers to the `half4` type by switching to pointers to the `half` type instead.  This should allow removal of `cl_khr_fp16`, because pointers to the `half` type used by the `vload_half` and `vstore_half` functions is in core OpenCL.

A better (but more involved) solution is to eliminate all usage of `half4`, `vload_half`, and `vstore_half`, period, and switch to float reference data instead.

Let's chat more tomorrow if you have questions - thanks!

**Comment by bashbaug** [comment]
I'm going to remove the "focused review" label until updates have been made.

**Comment by kamil-goras-mobica** [comment]
@bashbaug I created corrections in separate PR: https://github.com/KhronosGroup/OpenCL-CTS/pull/2147

**Comment by bashbaug** [comment]
I think this can be closed now, especially since #2147 is merged?

**Comment by kamil-goras-mobica** [comment]
@bashbaug Yes, this can be closed. Should I do it?

**Comment by bashbaug** [comment]
I think I confused myself on Tuesday's teleconference, sorry about that!

This PR can (and should) be closed.  I'll take care of that.  Thanks!

**Pull request closed without merging**
