### PR TITLE
Temporarily disable the test_kernel_attributes test case

### PR DESCRIPTION
**Pull request by fzou1**
Per OpenCL spec on CL_KERNEL_ATTRIBUTES, for kernels not created from OpenCL C
source and the clCreateProgramWithSource API call the string returned from this
query will be empty.
But in test_kernel_attributes test, it read from bc binary and expect to get
kernel attribute, which is not consistent with OpenCL spec.

### CODE REVIEW

**Comment by fzou1** [comment]
#1284

**Review by bashbaug — COMMENTED** [review]
Makes sense to me, the spec is pretty clear that `CL_KERNEL_ATTRIBUTES` is not supported when a program is not created from source.

There is an interesting question how other companies are passing this test since it has been around for a while, but I think it's OK to disable the test while we figure out what to do.

Note that this is an older SPIR test and not a SPIR-V test.

Needs a non-Intel reviewer - @kpet @alycm @Jeremy-Kemp ?

**Comment by alycm** [comment]
> There is an interesting question how other companies are passing this test since it has been around for a while, but I think it's OK to disable the test while we figure out what to do.

For SPIR we did return attributes for `CL_KERNEL_ATTRIBUTES`.  The 1.2 specification did not have the "the string returned from this query will be empty" line.  That was added in OpenCL 2.1, presumably as part of supporting IL programs.  The `cl_khr_spir` specification does not say anything about this query but I guess we implemented it to pass the test.

What changed is that https://github.com/KhronosGroup/OpenCL-CTS/pull/1055 added a test that enforces the empty string requirement.  Technically that only tests `clCreateProgramWithBinary` for device binaries, not SPIR binaries, but as they go through the same entry point it makes sense that implementations would behave consistently between the two cases.

Perhaps the unified specification accidentally made the OpenCL 1.0 -- 2.0 definition stricter, but the `cl_khr_spir` extension could have been implemented for 2.1+ as well, so the ambiguity isn't new.

**Review by alycm — APPROVED** [review]
Given we have two tests expecting contradicting behaviour I'm okay with disabling this test until that is resolved.

Disable this one rather than the other one because this one does not match the unified specification.

**Comment by fzou1** [comment]
Thank you. Could someone help merge this PR? I didn't have write access.

**Comment by Jeremy-Kemp** [comment]
> For SPIR we did return attributes for CL_KERNEL_ATTRIBUTES.

This is the same for our implementation as well. We will return attributes for SPIR inputs which explains why the test has been passing for us.

**Review by Jeremy-Kemp — APPROVED** [review]
OK to disable for now, with a proper fix in the future to close out #1284.

**Pull request merged**
