### PR TITLE
Synchronise with Khronos-private Gitlab branch

### PR DESCRIPTION
**Pull request by kpet**
The maintenance of the conformance tests is moving to Github.
    
This commit contains all the changes that have been done in
Gitlab since the first public release of the conformance tests.
    
Signed-off-by: Kevin Petit kevin.petit@arm.com

### CODE REVIEW

**Comment by gwawiork** [comment]
The issues I see in my execution:
- no spir directory in build
- make install should install some files in build products. Directories from tests compiler test, spirv_new, spir files
- test_conformance_api failed -> min_max_constant_buffer_size FAILED
- test_conformance_compatibility_api - 3 failed (one above) and two ERROR: device version string does not match required format!

**Comment by kpet** [comment]
Thanks for testing. Are these issues that you're not seeing with the `cl21_trunk` internal branch?

**Comment by gwawiork** [comment]
For sure I do not see them on Intel internal branch, I will check cl21_trunk

**Comment by gwawiork** [comment]
cl21_trunk has the same issues

**Comment by kpet** [comment]
Thanks, I'll merge this as is then.

**Pull request merged**
