### PR TITLE
Rename files for consistency

### PR DESCRIPTION
**Pull request by mantognini**

### CODE REVIEW

**Review by EwanC — APPROVED** [review]

**Review by gwawiork — APPROVED** [review]
LGTM

**Comment by gwawiork** [comment]
Some recent changes cause failures in my env on function `remquo` can you check on your side if it works properly on master ? Thanks !

**Comment by mantognini** [comment]
It works fine here. I ran `test_bruteforce -w remquo -1` and `test_bruteforce -w remquo -[65536]`.

I don't know the nature of the issue you're seeing but there was a bugfix #1152 that improved error handling in the relevant file. The other changes made recently should not have impacted the behaviour of the test in any way AFAIK. There was also #1153 but it's unlikely to be the issue if only remquo fails.

**Comment by gwawiork** [comment]
> It works fine here. I ran `test_bruteforce -w remquo -1` and `test_bruteforce -w remquo -[65536]`.
> 
> I don't know the nature of the issue you're seeing but there was a bugfix #1152 that improved error handling in the relevant file. The other changes made recently should not have impacted the behaviour of the test in any way AFAIK. There was also #1153 but it's unlikely to be the issue if only remquo fails.

I have kernel build errors. Looks like you have changed third argument of function from reference to value. Could you restore it?
https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/math_brute_force/binary_two_results_i.cpp#L141
There was (correct)
                       ` "( in1[i], in2[i], out2 + i );\n" `
Now we have (incorrect)
                        `"( in1[i], in2[i], out2[i] );\n"`

**Comment by mantognini** [comment]
Good catch! I've kept it correct on line 48 but not there. Will fix ASAP.

**Pull request merged**
