### PR TITLE
Vulkan: Use linear tiling

### PR DESCRIPTION
**Pull request by lakshmih**
The external memory sharing spec does not require
OpenCL to deduce if a Vulkan image is tiled or linear. Use tiled images.

Additionally, when selecting a queue family, the Vulkan implementation is not required to report the transfer bit for compute or graphics queues, it is implied.

### CODE REVIEW

**Comment by nikhiljnv** [comment]
#1530 has disabled these tests in CMake by default.
So, passing CI builds does not guarantee successful builds with the changes.
While the changes themselves are small and unlikely to cause any build breaks, I would encourage that we enable  these tests in CMake temporarily for future PRs to ensure we don't break the builds and turn off it again in CMake before merging the change. Alternatively, we can update presubmit  script to have VULKAN_IS_SUPPORTED option enabled by default so that CI builds don't skip these tests. I prefer latter.

**Comment by bcalidas** [comment]
HI Nikhil,

We do want to build and run these tests. Our recommendation is that supporting interop of Linear tiled Vulkan images with OpenCL is sufficient for an implementation to be conformant.

Thanks,
Balaji

**Comment by nikhiljnv** [comment]
> HI Nikhil,
> 
> We do want to build and run these tests. Our recommendation is that supporting interop of Linear tiled Vulkan images with OpenCL is sufficient for an implementation to be conformant.
> 
> Thanks, Balaji

Hi Balaji,
I am fine to keep conformance requirements minimal - Passing the test only for required (linear) tiling support should be sufficient.
However, not having test coverage for other tiling cases will prevent us not covering the underlying issues. In near future, we may want to address any special requirements for these cases in the spec. And to get there, it is important to have test coverage for different Vulkan formats and settings.
Any concerns keeping all the tiling types in the test and have an option to control which types to exercise with default being only linear tiling. Can think of similar needs for different memory flags. (Think of image sampler tests where certain addressing/ filtering modes are not required for conformance, but conformance tests cover the other non-mandatory modes as well that can be optionally run).

**Comment by bcalidas** [comment]
Hi Nikhil,

We are ok with adding an option for testing optimally tiled images as long as the default is linear. Should we update the PR with that option?

Thanks,
Balaji

**Comment by nikhiljnv** [comment]
> Hi Nikhil,
> 
> We are ok with adding an option for testing optimally tiled images as long as the default is linear. Should we update the PR with that option?
> 
> Thanks, Balaji

If it is a small change, prefer to do it as part of this PR. Otherwise, we can file a separate issue and/or fix it in a subsequent PR.

**Comment by bashbaug** [comment]
We don't say anything about tiling requirements in the external memory extension specification.  Should we?

**Comment by nikhiljnv** [comment]
> We don't say anything about tiling requirements in the external memory extension specification. Should we?

I have filed https://github.com/KhronosGroup/OpenCL-Docs/issues/861 to track the spec discussions and required changes to the spec.

**Comment by bashbaug** [comment]
Removing "focused review" while we figure out https://github.com/KhronosGroup/OpenCL-Docs/issues/861.

**Comment by lakshmih** [comment]
We will update this test as per final resolution of https://github.com/KhronosGroup/OpenCL-Docs/issues/861

**Comment by nikhiljnv** [comment]
@lakshmih 
Is this already taken care by #1676 ? Or do we still need to update this after latest spec changes?

**Comment by nikhiljnv** [comment]
Ping @lakshmih !! Is this still needed? If not, can we close?

**Pull request closed without merging**
