### PR TITLE
Use `clCreateProgramWithILKHR` on SPIR-V Offline Path

### PR DESCRIPTION
**Pull request by FranklandJack**
* Fall back on the `clCreateProgramWithILKHR` extension (if it exists)
in the case that the OpenCL driver does not have
`clCreateProgramWithIL` i.e. pre OpenCL-2.1. This enables drivers which
support the extension to test the SPIR-V offline compilation path.

### CODE REVIEW

**Comment by gwawiork** [comment]
This has been already fixed in PR #717 (not merged yet)

**Comment by FranklandJack** [comment]
> This has been already fixed in PR #717 (not merged yet)

Oops sorry, didn't see that one. Is there anything blocking us merging that?

**Comment by gwawiork** [comment]
I think PR is ready to be merged.

**Comment by alycm** [comment]
https://github.com/KhronosGroup/OpenCL-CTS/pull/717 is now merged so I believe that this is no longer required.

If I'm wrong then please reopen this PR @FranklandJack, but I'll close this for now.

**Pull request closed without merging**
