### PR TITLE
is_extension_available - extension not found in case of space in string pattern

### LINKED ISSUE #741: is_extension_available - white characters
After recent changes checking extension does not work in this [case](https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/d3d11/harness.cpp#L77). 
Open question: Should I remove spaces in the string or add method which will remove any white space automatically inside of is_extension_available ?

### PR DESCRIPTION
**Pull request by gwawiork**
Fixes #741

### CODE REVIEW

**Comment by gwawiork** [comment]
Ok will push only one commit fixing the issue.

**Comment by jrprice** [comment]
LGTM - needs formatting fix though.

**Comment by gwawiork** [comment]
Thanks. Format fixed

**Comment by kpet** [comment]
All the Travis jobs passed but Travis never reported back to Github. Merging.

**Pull request merged**
