### PR TITLE
Fix -Wreorder warnings

### PR DESCRIPTION
**Pull request by svenvh**
Initialize class members in the order in which they are declared in the class.

### CODE REVIEW

**Comment by EwanC** [comment]
Can we add `add_cxx_flag_if_supported(-Wreorder)` to the CMake to catch this going forward?

**Comment by svenvh** [comment]
> Can we add `add_cxx_flag_if_supported(-Wreorder)` to the CMake to catch this going forward?

Surely we could, but I'm hoping to enable `-Wall` soon (and I don't expect many new `Wreorder` errors to be introduced before then as new classes aren't being introduced that often).

I can still add it to CMakeLists if you wish, but in other PRs that fixed warnings I've only done so if I felt that new errors could be introduced easily (such as unused variables).

**Review by EwanC — APPROVED** [review]

**Comment by EwanC** [comment]
> Surely we could, but I'm hoping to enable -Wall soon (and I don't expect many new Wreorder errors to be introduced before then as new classes aren't being introduced that often).
>
> I can still add it to CMakeLists if you wish, but in other PRs that fixed warnings I've only done so if I felt that new errors could be introduced easily (such as unused variables).

Sound sensible, let's leave out modifying the CMake in this PR then

**Comment by bashbaug** [comment]
Merging as discussed in the December 13th teleconference.

**Pull request merged**
