### PR TITLE
add SPIR-V 1.4 testing for UserSemantic

### PR DESCRIPTION
**Pull request by bashbaug**
This PR adds targeted testing for more SPIR-V 1.4 features.  Specifically, this PR adds testing for OpDecorateString, OpMemberDecorateString, and the UserSemantic decoration.

### CODE REVIEW

**Comment by bashbaug** [comment]
There are several issues in the SPIR-V LLVM Translator so these tests probably won't pass for most implementations currently, see:

https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2460
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2670

I'll keep this as a "draft" until these issues are fixed.

**Comment by bashbaug** [comment]
This should be ready for review now.  I tested these tests with POCL and an up-to-date SPIR-V LLVM Translator and they both passed.

**Review by svenvh — APPROVED** [review]
LGTM (but needs a rebase)

**Comment by bashbaug** [comment]
I fixed the merge conflict in this PR and in #2122.  I don't have a strong opinion which goes in first.  If it's not this one though, I'll probably need to pull in the latest changes one more time.

**Review by svenvh — APPROVED** [review]
Reinstating my previous approval.

**Comment by bashbaug** [comment]
Merging as per agreement in the October 29th teleconference.

**Pull request merged**
