### PR TITLE
samplerlessReads: split out 1D Buffer testing into a separate test

### PR DESCRIPTION
**Pull request by kpet**
So we get finer grain reporting and better parallelisation in the future.

Signed-off-by: Kévin Petit <kpet@free.fr>

### CODE REVIEW

**Review by bashbaug — APPROVED** [review]
LGTM, just need to fix the code formatting so CI is happy.

**Review by lakshmih — APPROVED** [review]
Looks good.

Sreelakshmi Haridas Maruthur
Qualcomm

**Comment by kpet** [comment]
@bashbaug Now done, should be ready to go.

**Review by lakshmih — APPROVED** [review]
Sreelakshmi Haridas Maruthur
Qualcomm

**Pull request merged**
