### PR TITLE
Fix min version for SPIRV test registration.

### PR DESCRIPTION
**Pull request by JohnKesapidesARM**
Signed-off-by: John Kesapides <john.kesapides@arm.com>

### CODE REVIEW

**Comment by EwanC** [comment]
Does this change raise the minimum version required to run the spirv_new tests to [2.1](https://github.com/KhronosGroup/OpenCL-CTS/blob/41cd9c6d9823c15bdd09d3910f580ea39c8b2867/test_conformance/spirv_new/procs.h#L86)?

Our 1.2 implementation runs these tests with `clCreateProgramWithILKHR`

**Comment by JohnKesapidesARM** [comment]
Yeap you are right, the default version when no version is defined is 2.1. I'll change the default to 1.2. 
`#define TEST_SPIRV_FUNC(name) TEST_SPIRV_FUNC_VERSION(name, Version(2, 1))`. We still need the filtering to work properly for 2.2 tests

**Comment by JohnKesapidesARM** [comment]
@EwanC Should be ok now

**Review by EwanC — APPROVED** [review]
Looks good, thanks

**Review by gwawiork — APPROVED** [review]
LGTM

**Review by kpet — APPROVED** [review]

**Pull request merged**
