### PR TITLE
Enable mipmap extension pragmas

### LINKED ISSUE #598: image mipmap tests do not enable extensions
The clang OpenCL headers do not expose the image mipmap functions unless cl_khr_mipmap_image* are defined.  However the CTS generated kernel sources do not actually enable the extensions.  I assume they should be enabling the extensions before using them?

### PR DESCRIPTION
**Pull request by Jeremy-Kemp**
Fixes #598

### CODE REVIEW

**Comment by bashbaug** [comment]
Is this PR still required?  It looks like recent versions of Clang will compile kernels that use the mipmap built-in functions without an extension pragma.  Example: https://godbolt.org/z/dG65aTsTj

Note that Clang does currently require a kernel that uses the mipmap built-in functions to be compiled for OpenCL 2.0 or newer, so compiling with `-cl-std=CL1.2` (or omitting `-cl-std` entirely) will generate an error.  I'm not sure if this is a bug or intentional, but noting it for completeness.

If the PR is still required we should update the conclusions in https://github.com/KhronosGroup/OpenCL-Docs/issues/82, which currently include the mipmap extensions in the set of "extensions that do not require a pragma".

**Comment by Jeremy-Kemp** [comment]
It looks like the requirement to supply pragma was dropped in Clang 13, however we're still supporting implementations using Clang < 13.

Let me double check with our compiler team whether or not we *need* the pragma for these extensions to be present, or if we can patch Clang to allow this extension without the pragma.

**Comment by bashbaug** [comment]
In case it's helpful, I tested via Compiler Explorer all the way back to Clang 4 and it seems to work without the pragma, so the support has been around for a while, albeit still for OpenCL C 2.0 or newer: https://godbolt.org/z/MaxTYqxvs

**Review by bashbaug — APPROVED** [review]
I'm fine merging this as-is if it will help to make forward progress.  As observed, the pragmas shouldn't hurt anything, and this extension is already in the set of "should not produce a diagnostic" extensions, even if the pragma is not strictly required (see [comment](https://github.com/KhronosGroup/OpenCL-Docs/issues/82#issuecomment-786411529)).

I've verified that the only changes with this PR are the extension pragmas.

**Pull request merged**
